import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/Nav";
import Footer from "./ui/Footer";
import TutorsSlider from "./ui/TutorsSlider";
import Guides from "./ui/Guides";
import BecomeTutor from "./ui/BecomeTutor";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  infos,
  categories,
}: {
  children: React.ReactNode;
  infos: React.ReactNode;
  categories: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
        {infos}
        {categories}
        <TutorsSlider />
        <Guides />
        <BecomeTutor />
        <Footer />
      </body>
    </html>
  );
}
