import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./ui/Nav";
import Footer from "./ui/Footer";
import NextUIProvider from "./NextUIProvider";
import RootLayoutComponents from "./ui/RootLayoutComponents";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  infos,
  categories,
  guides,
  tutorslider,
  becomeTutor,
}: {
  children: React.ReactNode;
  infos: React.ReactNode;
  guides: React.ReactNode;
  categories: React.ReactNode;
  tutorslider: React.ReactNode;
  becomeTutor: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Nav />
          <RootLayoutComponents
  infos={infos}
  categories={categories}
  tutorslider={tutorslider}
  guides={guides}
  becomeTutor={becomeTutor}
>
  {children}
</RootLayoutComponents>
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
